calcAccSim <- function(res) {
  res$prop[is.na(res$prop)] <- ""
  res$type.plasmode[is.na(res$type.plasmode)] <- ""
  acc <- do.call(rbind, lapply(split(res, list(res$scenario, res$classifier, 
                                               res$type, res$type.plasmode, 
                                               res$prop), drop = TRUE), 
                               function(x) data.frame("Median\nRelative\nError" = median(x$Relative.Error.Accuracy), 
                                                      measure = "Accuracy", 
                                                      scenario = factor(x$scenario[1], levels = c("True Scenario", 
                                                                                                  "Shift: -0.5",
                                                                                                  "Shift: -0.25",
                                                                                                  "Shift: -0.125",
                                                                                                  "Shift: 0.125",  
                                                                                                  "Shift: 0.25",  
                                                                                                  "Shift: 0.5", 
                                                                                                  "Scale: 0.25",
                                                                                                  "Scale: 0.5",
                                                                                                  "Scale: 0.75", 
                                                                                                  "Scale: 1.33",
                                                                                                  "Scale: 2",
                                                                                                  "Scale: 4", 
                                                                                                  "Correlation: -0.2", 
                                                                                                  "Correlation: -0.1",
                                                                                                  "Correlation: 0", 
                                                                                                  "Correlation: 0.1", 
                                                                                                  "Correlation: 0.2", 
                                                                                                  "Distribution: Standard Normal", 
                                                                                                  "OGM scaled by: 0.5", 
                                                                                                  "OGM scaled by: 2",
                                                                                                  "OGM scaled by: 0")), 
                                                      classifier = gsub("Random Forest", "RF", x$classifier[1]), 
                                                      type = x$type[1], type.plasmode = x$type.plasmode[1], prop = x$prop[1], n = x$n[1], p = x$p[1])))
  rownames(acc) <- NULL
  auc <- do.call(rbind, lapply(split(res, list(res$scenario, res$classifier, 
                                               res$type, res$type.plasmode, 
                                               res$prop), drop = TRUE), 
                               function(x) data.frame("Median\nRelative\nError" = median(x$Relative.Error.AUC), 
                                                      measure = "AUC", 
                                                      scenario = factor(x$scenario[1], levels = c("True Scenario", 
                                                                                                  "Shift: -0.5",
                                                                                                  "Shift: -0.25",
                                                                                                  "Shift: -0.125",
                                                                                                  "Shift: 0.125",  
                                                                                                  "Shift: 0.25",  
                                                                                                  "Shift: 0.5", 
                                                                                                  "Scale: 0.25",
                                                                                                  "Scale: 0.5",
                                                                                                  "Scale: 0.75", 
                                                                                                  "Scale: 1.33",
                                                                                                  "Scale: 2",
                                                                                                  "Scale: 4", 
                                                                                                  "Correlation: -0.2", 
                                                                                                  "Correlation: -0.1",
                                                                                                  "Correlation: 0", 
                                                                                                  "Correlation: 0.1", 
                                                                                                  "Correlation: 0.2", 
                                                                                                  "Distribution: Standard Normal", 
                                                                                                  "OGM scaled by: 0.5", 
                                                                                                  "OGM scaled by: 2",
                                                                                                  "OGM scaled by: 0")), 
                                                      classifier = gsub("Random Forest", "RF", x$classifier[1]), 
                                                      type = x$type[1], type.plasmode = x$type.plasmode[1], prop = x$prop[1], n = x$n[1], p = x$p[1])))
  rownames(auc) <- NULL
  brier <- do.call(rbind, lapply(split(res, list(res$scenario, res$classifier, 
                                                 res$type, res$type.plasmode, 
                                                 res$prop), drop = TRUE), 
                                 function(x) data.frame("Median\nRelative\nError" = median(x$Relative.Error.Brier.Score), 
                                                        measure = "Brier Score", 
                                                        scenario = factor(x$scenario[1], levels = c("True Scenario", 
                                                                                                    "Shift: -0.5",
                                                                                                    "Shift: -0.25",
                                                                                                    "Shift: -0.125",
                                                                                                    "Shift: 0.125",  
                                                                                                    "Shift: 0.25",  
                                                                                                    "Shift: 0.5", 
                                                                                                    "Scale: 0.25",
                                                                                                    "Scale: 0.5",
                                                                                                    "Scale: 0.75", 
                                                                                                    "Scale: 1.33",
                                                                                                    "Scale: 2",
                                                                                                    "Scale: 4", 
                                                                                                    "Correlation: -0.2", 
                                                                                                    "Correlation: -0.1",
                                                                                                    "Correlation: 0", 
                                                                                                    "Correlation: 0.1", 
                                                                                                    "Correlation: 0.2", 
                                                                                                    "Distribution: Standard Normal", 
                                                                                                    "OGM scaled by: 0.5", 
                                                                                                    "OGM scaled by: 2",
                                                                                                    "OGM scaled by: 0")), 
                                                        classifier = gsub("Random Forest", "RF", x$classifier[1]), 
                                                        type = x$type[1], type.plasmode = x$type.plasmode[1], prop = x$prop[1], n = x$n[1], p = x$p[1])))
  rownames(brier) <- NULL
  
  f1 <- do.call(rbind, lapply(split(res, list(res$scenario, res$classifier, 
                                              res$type, res$type.plasmode, 
                                              res$prop), drop = TRUE), 
                              function(x) data.frame("Median\nRelative\nError" = median(x$Relative.Error.F1.Score), 
                                                     measure = "F1 Score", 
                                                     scenario = factor(x$scenario[1], levels = c("True Scenario", 
                                                                                                 "Shift: -0.5",
                                                                                                 "Shift: -0.25",
                                                                                                 "Shift: -0.125",
                                                                                                 "Shift: 0.125",  
                                                                                                 "Shift: 0.25",  
                                                                                                 "Shift: 0.5", 
                                                                                                 "Scale: 0.25",
                                                                                                 "Scale: 0.5",
                                                                                                 "Scale: 0.75", 
                                                                                                 "Scale: 1.33",
                                                                                                 "Scale: 2",
                                                                                                 "Scale: 4", 
                                                                                                 "Correlation: -0.2", 
                                                                                                 "Correlation: -0.1",
                                                                                                 "Correlation: 0", 
                                                                                                 "Correlation: 0.1", 
                                                                                                 "Correlation: 0.2", 
                                                                                                 "Distribution: Standard Normal", 
                                                                                                 "OGM scaled by: 0.5", 
                                                                                                 "OGM scaled by: 2",
                                                                                                 "OGM scaled by: 0")), 
                                                     classifier = gsub("Random Forest", "RF", x$classifier[1]), 
                                                     type = x$type[1], type.plasmode = x$type.plasmode[1], prop = x$prop[1], n = x$n[1], p = x$p[1])))
  rownames(f1) <- NULL
  
  sens <- do.call(rbind, lapply(split(res, list(res$scenario, res$classifier, 
                                                res$type, res$type.plasmode, 
                                                res$prop), drop = TRUE), 
                                function(x) data.frame("Median\nRelative\nError" = median(x$Relative.Error.Sensitivity), 
                                                       measure = "Sensitivity", 
                                                       scenario = factor(x$scenario[1], levels = c("True Scenario", 
                                                                                                   "Shift: -0.5",
                                                                                                   "Shift: -0.25",
                                                                                                   "Shift: -0.125",
                                                                                                   "Shift: 0.125",  
                                                                                                   "Shift: 0.25",  
                                                                                                   "Shift: 0.5", 
                                                                                                   "Scale: 0.25",
                                                                                                   "Scale: 0.5",
                                                                                                   "Scale: 0.75", 
                                                                                                   "Scale: 1.33",
                                                                                                   "Scale: 2",
                                                                                                   "Scale: 4", 
                                                                                                   "Correlation: -0.2", 
                                                                                                   "Correlation: -0.1",
                                                                                                   "Correlation: 0", 
                                                                                                   "Correlation: 0.1", 
                                                                                                   "Correlation: 0.2", 
                                                                                                   "Distribution: Standard Normal", 
                                                                                                   "OGM scaled by: 0.5", 
                                                                                                   "OGM scaled by: 2",
                                                                                                   "OGM scaled by: 0")), 
                                                       classifier = gsub("Random Forest", "RF", x$classifier[1]), 
                                                       type = x$type[1], type.plasmode = x$type.plasmode[1], prop = x$prop[1], n = x$n[1], p = x$p[1])))
  rownames(sens) <- NULL
  
  spec <- do.call(rbind, lapply(split(res, list(res$scenario, res$classifier, 
                                                res$type, res$type.plasmode, 
                                                res$prop), drop = TRUE), 
                                function(x) data.frame("Median\nRelative\nError" = median(x$Relative.Error.Specificity), 
                                                       measure = "Specificity", 
                                                       scenario = factor(x$scenario[1], levels = c("True Scenario", 
                                                                                                   "Shift: -0.5",
                                                                                                   "Shift: -0.25",
                                                                                                   "Shift: -0.125",
                                                                                                   "Shift: 0.125",  
                                                                                                   "Shift: 0.25",  
                                                                                                   "Shift: 0.5", 
                                                                                                   "Scale: 0.25",
                                                                                                   "Scale: 0.5",
                                                                                                   "Scale: 0.75", 
                                                                                                   "Scale: 1.33",
                                                                                                   "Scale: 2",
                                                                                                   "Scale: 4", 
                                                                                                   "Correlation: -0.2", 
                                                                                                   "Correlation: -0.1",
                                                                                                   "Correlation: 0", 
                                                                                                   "Correlation: 0.1", 
                                                                                                   "Correlation: 0.2", 
                                                                                                   "Distribution: Standard Normal", 
                                                                                                   "OGM scaled by: 0.5", 
                                                                                                   "OGM scaled by: 2",
                                                                                                   "OGM scaled by: 0")), 
                                                       classifier = gsub("Random Forest", "RF", x$classifier[1]), 
                                                       type = x$type[1], type.plasmode = x$type.plasmode[1], prop = x$prop[1], n = x$n[1], p = x$p[1])))
  
  median.err <- rbind(acc, auc, brier, f1, sens, spec)
  # median.err <- reshape(median.err, direction = "long", 
  #                       varying = c("Ridge", "LASSO", "SVM", "KNN", "Random.Forest"), 
  #                       v.names = "Median\nRelative\nError", timevar = "classifier", 
  #                       times = c("Ridge", "LASSO", "SVM", "KNN", "Random.Forest"), 
  #                       idvar = c("scenario", "measure"))
  # rownames(median.err) <- NULL
  # median.err$classifier <- gsub("Random Forest", "RF", median.err$classifier)
  # median.err$scenario <- factor(median.err$scenario, 
  #                               levels = c("True Scenario", 
  #                                          "Shift: -0.5",
  #                                          "Shift: -0.25",
  #                                          "Shift: -0.125",
  #                                          "Shift: 0.125",  
  #                                          "Shift: 0.25",  
  #                                          "Shift: 0.5", 
  #                                          "Scale: 0.25",
  #                                          "Scale: 0.5",
  #                                          "Scale: 0.75", 
  #                                          "Scale: 1.33",
  #                                          "Scale: 2",
  #                                          "Scale: 4", 
  #                                          "Correlation: -0.2", 
  #                                          "Correlation: -0.1",
  #                                          "Correlation: 0", 
  #                                          "Correlation: 0.1", 
  #                                          "Correlation: 0.2", 
  #                                          "Distribution: Standard Normal", 
  #                                          "OGM scaled by: 0.5", 
  #                                          "OGM scaled by: 2",
  #                                          "OGM scaled by: 0"))
  
  thresh <- tapply(res[res$type == "parametric" & res$scenario == "True Scenario", "Relative.Error.Accuracy"], 
                   list(res[res$type == "parametric" & res$scenario == "True Scenario", "classifier"]), 
                   function(x) quantile(x, c(0.025, 0.975)))
  
  acc <- do.call(rbind, lapply(split(res, list(res$scenario, res$classifier, 
                                               res$type, res$type.plasmode, 
                                               res$prop), drop = TRUE), 
                               function(x) data.frame("Proportion\nAcceptable\nSimulations" = mean(x$Relative.Error.Accuracy <= thresh[[x$classifier[1]]][2] & 
                                                                                                     x$Relative.Error.Accuracy >= thresh[[x$classifier[1]]][1]), 
                                                      measure = "Accuracy", 
                                                      scenario = factor(x$scenario[1], levels = c("True Scenario", 
                                                                                                  "Shift: -0.5",
                                                                                                  "Shift: -0.25",
                                                                                                  "Shift: -0.125",
                                                                                                  "Shift: 0.125",  
                                                                                                  "Shift: 0.25",  
                                                                                                  "Shift: 0.5", 
                                                                                                  "Scale: 0.25",
                                                                                                  "Scale: 0.5",
                                                                                                  "Scale: 0.75", 
                                                                                                  "Scale: 1.33",
                                                                                                  "Scale: 2",
                                                                                                  "Scale: 4", 
                                                                                                  "Correlation: -0.2", 
                                                                                                  "Correlation: -0.1",
                                                                                                  "Correlation: 0", 
                                                                                                  "Correlation: 0.1", 
                                                                                                  "Correlation: 0.2", 
                                                                                                  "Distribution: Standard Normal", 
                                                                                                  "OGM scaled by: 0.5", 
                                                                                                  "OGM scaled by: 2",
                                                                                                  "OGM scaled by: 0")), 
                                                      classifier = gsub("Random Forest", "RF", x$classifier[1]), 
                                                      type = x$type[1], type.plasmode = x$type.plasmode[1], prop = x$prop[1], n = x$n[1], p = x$p[1])))
  rownames(acc) <- NULL
  
  thresh <- tapply(res[res$type == "parametric" & res$scenario == "True Scenario", "Relative.Error.AUC"], 
                   list(res[res$type == "parametric" & res$scenario == "True Scenario", "classifier"]), 
                   function(x) quantile(x, c(0.025, 0.975)))
  
  auc <- do.call(rbind, lapply(split(res, list(res$scenario, res$classifier, 
                                               res$type, res$type.plasmode, 
                                               res$prop), drop = TRUE), 
                               function(x) data.frame("Proportion\nAcceptable\nSimulations" = mean(x$Relative.Error.AUC <= thresh[[x$classifier[1]]][2] & 
                                                                                                     x$Relative.Error.AUC >= thresh[[x$classifier[1]]][1]), 
                                                      measure = "AUC", 
                                                      scenario = factor(x$scenario[1], levels = c("True Scenario", 
                                                                                                  "Shift: -0.5",
                                                                                                  "Shift: -0.25",
                                                                                                  "Shift: -0.125",
                                                                                                  "Shift: 0.125",  
                                                                                                  "Shift: 0.25",  
                                                                                                  "Shift: 0.5", 
                                                                                                  "Scale: 0.25",
                                                                                                  "Scale: 0.5",
                                                                                                  "Scale: 0.75", 
                                                                                                  "Scale: 1.33",
                                                                                                  "Scale: 2",
                                                                                                  "Scale: 4", 
                                                                                                  "Correlation: -0.2", 
                                                                                                  "Correlation: -0.1",
                                                                                                  "Correlation: 0", 
                                                                                                  "Correlation: 0.1", 
                                                                                                  "Correlation: 0.2", 
                                                                                                  "Distribution: Standard Normal", 
                                                                                                  "OGM scaled by: 0.5", 
                                                                                                  "OGM scaled by: 2",
                                                                                                  "OGM scaled by: 0")), 
                                                      classifier = gsub("Random Forest", "RF", x$classifier[1]), 
                                                      type = x$type[1], type.plasmode = x$type.plasmode[1], prop = x$prop[1], n = x$n[1], p = x$p[1])))
  rownames(auc) <- NULL
  
  thresh <- tapply(res[res$type == "parametric" & res$scenario == "True Scenario", "Relative.Error.Brier.Score"], 
                   list(res[res$type == "parametric" & res$scenario == "True Scenario", "classifier"]), 
                   function(x) quantile(x, c(0.025, 0.975)))
  
  brier <- do.call(rbind, lapply(split(res, list(res$scenario, res$classifier, 
                                                 res$type, res$type.plasmode, 
                                                 res$prop), drop = TRUE), 
                                 function(x) data.frame("Proportion\nAcceptable\nSimulations" = mean(x$Relative.Error.Brier.Score <= thresh[[x$classifier[1]]][2] & 
                                                                                                       x$Relative.Error.Brier.Score >= thresh[[x$classifier[1]]][1]), 
                                                        measure = "Brier Score", 
                                                        scenario = factor(x$scenario[1], levels = c("True Scenario", 
                                                                                                    "Shift: -0.5",
                                                                                                    "Shift: -0.25",
                                                                                                    "Shift: -0.125",
                                                                                                    "Shift: 0.125",  
                                                                                                    "Shift: 0.25",  
                                                                                                    "Shift: 0.5", 
                                                                                                    "Scale: 0.25",
                                                                                                    "Scale: 0.5",
                                                                                                    "Scale: 0.75", 
                                                                                                    "Scale: 1.33",
                                                                                                    "Scale: 2",
                                                                                                    "Scale: 4", 
                                                                                                    "Correlation: -0.2", 
                                                                                                    "Correlation: -0.1",
                                                                                                    "Correlation: 0", 
                                                                                                    "Correlation: 0.1", 
                                                                                                    "Correlation: 0.2", 
                                                                                                    "Distribution: Standard Normal", 
                                                                                                    "OGM scaled by: 0.5", 
                                                                                                    "OGM scaled by: 2",
                                                                                                    "OGM scaled by: 0")), 
                                                        classifier = gsub("Random Forest", "RF", x$classifier[1]), 
                                                        type = x$type[1], type.plasmode = x$type.plasmode[1], prop = x$prop[1], n = x$n[1], p = x$p[1])))
  rownames(brier) <- NULL
  
  thresh <- tapply(res[res$type == "parametric" & res$scenario == "True Scenario", "Relative.Error.F1.Score"], 
                   list(res[res$type == "parametric" & res$scenario == "True Scenario", "classifier"]), 
                   function(x) quantile(x, c(0.025, 0.975)))
  
  f1 <- do.call(rbind, lapply(split(res, list(res$scenario, res$classifier, 
                                              res$type, res$type.plasmode, 
                                              res$prop), drop = TRUE), 
                              function(x) data.frame("Proportion\nAcceptable\nSimulations" = mean(x$Relative.Error.F1.Score <= thresh[[x$classifier[1]]][2] & 
                                                                                                    x$Relative.Error.F1.Score >= thresh[[x$classifier[1]]][1]), 
                                                     measure = "F1 Score", 
                                                     scenario = factor(x$scenario[1], levels = c("True Scenario", 
                                                                                                 "Shift: -0.5",
                                                                                                 "Shift: -0.25",
                                                                                                 "Shift: -0.125",
                                                                                                 "Shift: 0.125",  
                                                                                                 "Shift: 0.25",  
                                                                                                 "Shift: 0.5", 
                                                                                                 "Scale: 0.25",
                                                                                                 "Scale: 0.5",
                                                                                                 "Scale: 0.75", 
                                                                                                 "Scale: 1.33",
                                                                                                 "Scale: 2",
                                                                                                 "Scale: 4", 
                                                                                                 "Correlation: -0.2", 
                                                                                                 "Correlation: -0.1",
                                                                                                 "Correlation: 0", 
                                                                                                 "Correlation: 0.1", 
                                                                                                 "Correlation: 0.2", 
                                                                                                 "Distribution: Standard Normal", 
                                                                                                 "OGM scaled by: 0.5", 
                                                                                                 "OGM scaled by: 2",
                                                                                                 "OGM scaled by: 0")), 
                                                     classifier = gsub("Random Forest", "RF", x$classifier[1]), 
                                                     type = x$type[1], type.plasmode = x$type.plasmode[1], prop = x$prop[1], n = x$n[1], p = x$p[1])))
  rownames(f1) <- NULL
  
  thresh <- tapply(res[res$type == "parametric" & res$scenario == "True Scenario", "Relative.Error.Sensitivity"], 
                   list(res[res$type == "parametric" & res$scenario == "True Scenario", "classifier"]), 
                   function(x) quantile(x, c(0.025, 0.975)))
  
  sens <- do.call(rbind, lapply(split(res, list(res$scenario, res$classifier, 
                                                res$type, res$type.plasmode, 
                                                res$prop), drop = TRUE), 
                                function(x) data.frame("Proportion\nAcceptable\nSimulations" = mean(x$Relative.Error.Sensitivity <= thresh[[x$classifier[1]]][2] & 
                                                                                                      x$Relative.Error.Sensitivity >= thresh[[x$classifier[1]]][1]), 
                                                       measure = "Sensitivity", 
                                                       scenario = factor(x$scenario[1], levels = c("True Scenario", 
                                                                                                   "Shift: -0.5",
                                                                                                   "Shift: -0.25",
                                                                                                   "Shift: -0.125",
                                                                                                   "Shift: 0.125",  
                                                                                                   "Shift: 0.25",  
                                                                                                   "Shift: 0.5", 
                                                                                                   "Scale: 0.25",
                                                                                                   "Scale: 0.5",
                                                                                                   "Scale: 0.75", 
                                                                                                   "Scale: 1.33",
                                                                                                   "Scale: 2",
                                                                                                   "Scale: 4", 
                                                                                                   "Correlation: -0.2", 
                                                                                                   "Correlation: -0.1",
                                                                                                   "Correlation: 0", 
                                                                                                   "Correlation: 0.1", 
                                                                                                   "Correlation: 0.2", 
                                                                                                   "Distribution: Standard Normal", 
                                                                                                   "OGM scaled by: 0.5", 
                                                                                                   "OGM scaled by: 2",
                                                                                                   "OGM scaled by: 0")), 
                                                       classifier = gsub("Random Forest", "RF", x$classifier[1]), 
                                                       type = x$type[1], type.plasmode = x$type.plasmode[1], prop = x$prop[1], n = x$n[1], p = x$p[1])))
  rownames(sens) <- NULL
  
  thresh <- tapply(res[res$type == "parametric" & res$scenario == "True Scenario", "Relative.Error.Specificity"], 
                   list(res[res$type == "parametric" & res$scenario == "True Scenario", "classifier"]), 
                   function(x) quantile(x, c(0.025, 0.975)))
  
  spec <- do.call(rbind, lapply(split(res, list(res$scenario, res$classifier, 
                                                res$type, res$type.plasmode, 
                                                res$prop), drop = TRUE), 
                                function(x) data.frame("Proportion\nAcceptable\nSimulations" = mean(x$Relative.Error.Specificity <= thresh[[x$classifier[1]]][2] & 
                                                                                                      x$Relative.Error.Specificity >= thresh[[x$classifier[1]]][1]), 
                                                       measure = "Specificity", 
                                                       scenario = factor(x$scenario[1], levels = c("True Scenario", 
                                                                                                   "Shift: -0.5",
                                                                                                   "Shift: -0.25",
                                                                                                   "Shift: -0.125",
                                                                                                   "Shift: 0.125",  
                                                                                                   "Shift: 0.25",  
                                                                                                   "Shift: 0.5", 
                                                                                                   "Scale: 0.25",
                                                                                                   "Scale: 0.5",
                                                                                                   "Scale: 0.75", 
                                                                                                   "Scale: 1.33",
                                                                                                   "Scale: 2",
                                                                                                   "Scale: 4", 
                                                                                                   "Correlation: -0.2", 
                                                                                                   "Correlation: -0.1",
                                                                                                   "Correlation: 0", 
                                                                                                   "Correlation: 0.1", 
                                                                                                   "Correlation: 0.2", 
                                                                                                   "Distribution: Standard Normal", 
                                                                                                   "OGM scaled by: 0.5", 
                                                                                                   "OGM scaled by: 2",
                                                                                                   "OGM scaled by: 0")), 
                                                       classifier = gsub("Random Forest", "RF", x$classifier[1]), 
                                                       type = x$type[1], type.plasmode = x$type.plasmode[1], prop = x$prop[1], n = x$n[1], p = x$p[1])))
  rownames(spec) <- NULL
  acc.sims <- rbind(acc, auc, brier, f1, sens, spec)
  colnames(acc.sims)[1] <- "Proportions\nAcceptable\nIterations"
  colnames(median.err)[1] <- "Median\nRelative\nError"
  acc.sims$classifier <- factor(acc.sims$classifier, levels = rev(c("Ridge", "LASSO", "SVM", "KNN", "RF")))
  median.err$classifier <- factor(median.err$classifier, levels = rev(c("Ridge", "LASSO", "SVM", "KNN", "RF")))
  return(list(accept.sims = acc.sims, median.err = median.err))
}

plotAccSim <- function(res, option = "C"){
  dat <- res$accept.sims
  dat$measure[dat$measure == "F1 Score"] <- "F[1]~Score"
  dat$measure[dat$measure == "Brier Score"] <- "Brier~Score"
  ggplot(dat, aes(y = classifier, x = scenario, fill = `Proportions\nAcceptable\nIterations`)) + 
    facet_nested(measure ~ type + type.plasmode + prop, scales = "free_x", 
                 space = "free_x", labeller = label_parsed) + 
    geom_tile(color = "white", lwd = 0.5, linetype = 1) + 
    theme_bw() + 
    theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1, size = 15), 
          text = element_text(size = 17), 
          title = element_text(size = 15),
          axis.title = element_text(size = 15), 
          axis.text = element_text(size = 15), 
          strip.background = element_rect(fill="white"), 
          strip.text = element_text(size = 15)) + 
    ylab("Classifier") + xlab ("Scenario") + 
    viridis::scale_fill_viridis(limits = c(0, 1), breaks=seq(0, 1, by = 0.25),
                                option = option, direction = -1)
}

plotMedErr <- function(res, option = "C"){
  dat <- res$median.err
  ggplot(dat, aes(y = classifier, x = scenario, 
                  fill = `Median\nRelative\nError`)) + 
    facet_nested(measure ~ type + type.plasmode + prop, scales = "free_x", 
                 space = "free_x") + geom_tile() + theme_bw() + 
    theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1, size = 15), 
          text = element_text(size = 17), 
          title = element_text(size = 15),
          axis.title = element_text(size = 15), 
          axis.text = element_text(size = 15), 
          strip.background = element_rect(fill="white"), 
          strip.text = element_text(size = 15)) + 
    ylab("Classifier") + xlab ("Scenario") + 
    viridis::scale_fill_viridis(limits = c(0, 1), breaks=seq(0, 1, by = 0.25), 
                                option = option, direction = -1) 
}

